---
platform: linux

image_resource:
  type: docker-image
  source: { repository: betomorrow/docker-awsebcli }

inputs:
  - name: ci-pipeline
  - name: graphql-artifact

run:
  path: ci-pipeline/tasks/deploy/deploy.sh
